// Generates the web's token CSS from the TS source of truth. Run with plain
// Node (>=22 strips TS types): `node packages/tokens/build-css.ts`. Re-run
// after editing palette.ts / scale.ts. The two outputs are committed so the
// app builds without a codegen step; they are DERIVED — never hand-edit them.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve as resolvePath } from "node:path";
import { rootVars, themeVars, toCssDecls } from "./cssvars";

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = resolvePath(here, "../../apps/web/app/styles");

const banner = (src: string) =>
  `/* GENERATED by @atlas/tokens (build-css.ts) — do not edit.\n` +
  `   Edit packages/tokens/${src} and re-run \`node packages/tokens/build-css.ts\`. */\n`;

const tokensCss = `${banner("palette.ts / scale.ts")}:root {\n${toCssDecls(rootVars)}\n}\n`;

const themeCss =
  `${banner("palette.ts / scale.ts")}@theme inline {\n${toCssDecls(themeVars)}\n}\n`;

writeFileSync(resolvePath(stylesDir, "tokens.generated.css"), tokensCss);
writeFileSync(resolvePath(stylesDir, "theme.generated.css"), themeCss);

console.log(
  `Wrote tokens.generated.css (${rootVars.length} vars) and ` +
    `theme.generated.css (${themeVars.length} vars).`,
);
